### ISSUE TITLE
Angle typo as Angel

### ISSUE THREAD

**Issue by kengreim** [malstraem/arinc424.net#6]
The following should be `VerticalAngle` not `VerticalAngel`

https://github.com/malstraem/arinc424.net/blob/5c9b5ed184c4748b432f71d15270352d74c0c384/source/records/procedures/ArrivalPoint.cs#L12

https://github.com/malstraem/arinc424.net/blob/5c9b5ed184c4748b432f71d15270352d74c0c384/source/records/procedures/ApproachPoint.cs#L12

**Comment by malstraem** [comment]
Thanks! Will be fixed with the next commit 🤓

**Comment by malstraem** [comment]
Fixed #7
